import { Injectable } from '@angular/core';
import { Education } from './education/education';
import { Project } from './project/project';
import { Skill } from './skills/skill';
import { Work } from './work/work';
import { Contact } from './contact/contact';

export const skillsArray: Skill[] = [
  {
    description: 'Web-based languages',
    details: [
      { detail: 'HTML5' },
      { detail: 'SCSS', link: 'https://sass-lang.com/' },
      { detail: 'CSS' },
      { detail: 'TypeScript', link: 'https://www.typescriptlang.org/' },
      { detail: 'JavaScript' },
      { detail: 'PHP', link: 'https://secure.php.net/' },
      { detail: 'Python', link: 'https://www.python.org/' }
    ]
  },
  {
    description: 'Front-end frameworks',
    details: [
      { detail: 'AngularJS', link: 'https://angularjs.org/' },
      { detail: 'Angular', link: 'https://angular.io/' },
      { detail: 'Bootstrap', link: 'https://getbootstrap.com/' },
      { detail: 'jQuery', link: 'https://jquery.com/' },
      { detail: 'WordPress', link: 'https://wordpress.org/' },
      { detail: 'Flask', link: 'http://flask.pocoo.org/' }
    ]
  },
  {
    description: 'Programming languages',
    details: [
      { detail: 'C family', points: [
          { detail: 'C' },
          { detail: 'C++' },
          { detail: 'C#' }
        ]
      },
      { detail: 'Java', link: 'https://www.java.com/en/' },
      { detail: 'Various others with minimal experience' }
    ]
  },
  {
    description: 'Project structure',
    details: [
      { detail: 'Test-driven development' },
      { detail: 'Dependency injection' },
      { detail: 'Inversion of control' },
      { detail: 'Object-oriented programming' },
      { detail: 'Continuous integration' },
      { detail: 'REST API calls to protect sensitive data' }
    ]
  },
  {
    description: 'Project management',
    details: [
      { detail: 'Experience with Agile practices using SCRUM meetings' },
      { detail: 'Used waterfall methodologies on a couple small projects in college' },
      { detail: 'Used Git as source control management', link: 'https://git-scm.com/' },
      { detail: 'Used Docker to create containers to simulate required services during development',
        link: 'https://www.docker.com/' }
    ]
  },
  {
    description: 'Operating systems',
    details: [
      { detail: 'Windows' },
      { detail: 'Linux', points: [
          { detail: 'Mint', link: 'https://linuxmint.com/' },
          { detail: 'Ubuntu', link: 'https://www.ubuntu.com/' }
        ]
      }
    ]
  },
  {
    description: 'Server-side development',
    details: [
      { detail: 'Used PHP for application' },
      { detail: 'Used MySQL for 3NF data management', link: 'https://www.mysql.com/' },
      { detail: 'Converted MySQL to JSON when pulling data to application' },
      { detail: 'Converted JSON to MySQL when submitting data to database' }
    ]
  },
  {
    description: 'Soft skills',
    details: [
      { detail: 'Works well with others as well as individually' },
      { detail: 'Passionate about developing software to solve a problem' },
      { detail: 'Learns programming and scripting languages quickly' },
      { detail: 'Strong analytical and problem solving skills' }
    ]
  }
];

export const projectArray: Project[] = [
  {
    title: 'Cambria Internal Applications',
    details: [
      { detail: 'Developed AngularJS single-page applications with ui-router to manage states' },
      { detail: 'Created C# services for a REST API called by AngularJS apps' },
      { detail: 'Implemented unit tests using Jasmine for AngularJS apps and Moq for testing C# services' },
      { detail: 'Dependency Injection design to enhance quality of unit tests by mocking dependencies' },
      { detail: 'Separation of Concerns ensured properly encapsulated and maintainable code' },
      { detail: 'Analyze logs in ELK stack generated by API service calls to locate and address errors' }
    ]
  },
  {
    title: 'Interactive Resume',
    details: [
      { detail: 'Created an interactive single-page application using Angular router to learn how to use newer versions of Angular' },
      { detail: 'Used Bootstrap 4 to style a responsive layout and learn differences from Bootstrap 3',
        link: 'https://getbootstrap.com/' },
      { detail: 'Allowed me to provide more information about myself since I was unable to fit it all on a single page resume' },
      { detail: 'Used Angular CLI to generate all components and services, as well as test and run the application',
        link: 'https://angular.io/' },
      { detail: 'Used Lodash to sort data array to ensure grid tiles are in the proper order in the work and education pages',
        link: 'https://lodash.com/' },
      { detail: 'Used free Font Awesome icons in the navbar',
        link: 'https://fontawesome.com/' },
      { detail: 'Most data is contained in a service, which is then displayed in template HTML files for each component' },
      { detail: 'Service file uses async methods to simulate database connection and make it easy to connect a real one instead' },
      { detail: 'Each component gets data from service, then resolves it before display is updated' },
      { detail: 'Continuous integration through Travis CI, which automatically runs code linting, unit and e2e tests,' +
        ' builds the project, and deploys it to my Github Pages when changes are submitted to my repo',
        link: 'https://travis-ci.org/' }
    ]
  }
];

export const workArray: Work[] = [
  {
    name: 'Pablo\'s Mexican Restaurant',
    startMonth: 'August',
    startYear: '2012',
    endMonth: 'November',
    endYear: '2014',
    position: 'Table clearer',
    points: [
      'Worked in a fast-paced environment',
      'Helped out the restaurant by being a helpful member of the team'
    ]
  },
  {
    name: 'Concordia State University, St. Paul',
    startMonth: 'March',
    startYear: '2017',
    endMonth: 'April',
    endYear: '2017',
    position: 'Temporary grading assistant',
    points: [
      'Assisted the teacher of the course by providing fair and ' +
        'accurate grades in a timely manner',
      'Analyzed the code and attempted to run each project to determine scores'
    ]
  },
  {
    name: 'Cub Foods',
    startMonth: 'August',
    startYear: '2015',
    endMonth: 'April',
    endYear: '2018',
    position: 'Cashier, Self-checkout supervisor',
    points: [
      'Improved my multitasking skills by managing multiple registers',
      'Used my customer service skills to assist our customers'
    ]
  },
  {
    name: 'Cambria',
    startMonth: 'April',
    startYear: '2018',
    endMonth: 'October',
    endYear: '2018',
    position: 'Development engineer intern',
    points: [
      'Worked with AngularJS to create front-end components',
      'Created additional methods for a C# microservice back-end',
      'Connected components to microservices through a REST API'
    ]
  }
];

export const educationArray: Education[] = [
  {
    name: 'Normandale Community College',
    startMonth: 'August',
    startYear: '2012',
    endMonth: 'May',
    endYear: '2015',
    graduated: false,
    degree: null,
    transfered: true,
    transferedLocation: 'Concordia State University, St. Paul',
    points: [
      'GPA of 3.73',
      'Member of Phi Theta Kappa Honor Society'
    ]
  },
  {
    name: 'Concordia State University, St. Paul',
    startMonth: 'September',
    startYear: '2015',
    endMonth: 'June',
    endYear: '2018',
    graduated: true,
    degree: 'BS of Computer Science',
    transfered: false,
    transferedLocation: null,
    points: [
      'Graduated Summa Cum Laude',
      'GPA of 3.78',
      'Group leader in Programming and Problem Solving',
      'Lead programmer in Object-Oriented Programming and in Modern Web Design'
    ]
  }
];

export const contactArray: Contact[] = [
  {
    label: 'Email',
    detail: 'jacobgast@gmail.com'
  },
  {
    label: 'Phone',
    detail: '(651) 373-7581'
  },
  {
    label: 'Mailing Address',
    detail: '13300 Ann Pl., Shakopee, MN 55379'
  },
  {
    label: 'LinkedIn',
    detail: 'https://www.linkedin.com/in/jacob-gast/',
    isLink: true
  }
];

@Injectable({
  providedIn: 'root'
})

export class DataService {

  constructor() { }

  // All functions defined as async to simulate data returned from API call.
  // Home and 404 pages do not fetch this data, as it doesn't change often,
  // so it's slightly more efficient to hardcode those pages

  public async getSkills(): Promise<Skill[]> {
    return skillsArray;
  }

  public async getProjects(): Promise<Project[]> {
    return projectArray;
  }

  public async getWork(): Promise<Work[]> {
    return workArray;
  }

  public async getEducation(): Promise<Education[]> {
    return educationArray;
  }

  public async getContacts(): Promise<Contact[]> {
    return contactArray;
  }
}
